### ISSUE TITLE
this works with windows 7,8,10?

### ISSUE THREAD

**Issue by Axe-Usa** [turbo/zero2hero#1]
Hi i was trying to create the rule but i couldn't i used this:
strcat(curPath, "mypath");
Can you explain how the program works to can use it?

**Comment by Axe-Usa** [comment]
Hi why your program never create the regedit rule of my foobar executable??

**Comment by turbo** [comment]
This is a port. For references about the operation, refer to the source. I will not help you here. Damage can be done with this and you are clearly unfit to handle this simple tool.
