### ISSUE TITLE
Damage some one for copy a rule in Software\\Classes\\mscfile\\shell\\open\\command?

### ISSUE THREAD

**Issue by Omardavinci** [turbo/zero2hero#2]
Are you saying someone can do damage with thisdiscover? i dude that buddy, the responsability must to have microsoft for not take more protection to UAC. Sorry buddy but i should reply you. I know how to compile this program only that my antivirus was blocking something of your program for this i was asking. bye Axe-Usa.

**Comment by turbo** [comment]
UAC is not a security barrier. Bug reports towards the "circumvention" of UAC are neither elevated nor treated as security incidents. Why am I saying this? Because I can't begin to comprehend the mess that is your comment, apart from the usual sneering at UAC.
